"""Create search index on mock_items

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-05 23:41:02.381417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('entity_id', sa.String(length=255), nullable=False))
    op.add_column('knowledge_base', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('knowledge_base', sa.Column('fact_type', sa.String(length=50), nullable=False))
    op.add_column('knowledge_base', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('knowledge_base', sa.Column('relations', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('knowledge_base', sa.Column('embedding', Vector(dim=384), nullable=False))
    op.add_column('knowledge_base', sa.Column('search_text_bm25', sa.String(), nullable=False))
    op.add_column('knowledge_base', sa.Column('rich_context', sa.String(), nullable=False))
    op.alter_column('knowledge_base', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('knowledge_base', 'in_stock')
    op.drop_column('knowledge_base', 'last_updated_date')
    op.drop_column('knowledge_base', 'rating')
    op.drop_column('knowledge_base', 'metadata')
    op.drop_column('knowledge_base', 'category')
    op.drop_column('knowledge_base', 'latest_available_time')
    op.drop_column('knowledge_base', 'weight_range')
    op.drop_column('knowledge_base', 'created_at')
    op.drop_column('knowledge_base', 'description')
    op.create_bm25_index('search_idx', 'knowledge_base', ['id', 'search_text_bm25'], key_field='id', table_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('search_idx', if_exists=True, schema='public')
    op.add_column('knowledge_base', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('weight_range', postgresql.INT4RANGE(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('latest_available_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('last_updated_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('knowledge_base', 'id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('knowledge_base', 'rich_context')
    op.drop_column('knowledge_base', 'search_text_bm25')
    op.drop_column('knowledge_base', 'embedding')
    op.drop_column('knowledge_base', 'relations')
    op.drop_column('knowledge_base', 'content')
    op.drop_column('knowledge_base', 'fact_type')
    op.drop_column('knowledge_base', 'domain')
    op.drop_column('knowledge_base', 'entity_id')
    # ### end Alembic commands ###
