"""Create search index on mock_items

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-05 13:23:17.807784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('idx_kb_bm25', if_exists=True, schema='public', table_name='knowledge_base', expressions=['search_text_bm25'], key_field='id')
    op.create_bm25_index('search_idx', 'knowledge_base', ['id', 'search_text_bm25'], key_field='id', table_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('search_idx', if_exists=True, schema='public')
    op.create_bm25_index('idx_kb_bm25', 'knowledge_base', ['search_text_bm25'], key_field='id', table_schema='public')
    # ### end Alembic commands ###
